language: julia
os:
  - linux
julia:
  - 0.3
notifications:
  email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("FinancialAnalytics"); Pkg.test("FinancialAnalytics")'
